    zn "%SYS"

    // Unexpire passwords and set up passwordless mode to simplify dev use.
    // ** Comment out these two line for Production use **
    do ##class(Security.Users).UnExpireUserPasswords("*")
    zpm "install passwordless"

    zn "USER"

    // Create /_vscode web app to support intersystems-community.testingmanager VS Code extension
    zpm "install vscode-per-namespace-settings"

    zpm "load /home/irisowner/dev/ -v":1:1
    halt
