Class UnitTest.isc.json.notJSONAdapted Extends %Persistent
{

Storage Default
{
<Data name="NotJSONAdaptedDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^UnitTest.App469.NotJSONAdaptedD</DataLocation>
<DefaultData>NotJSONAdaptedDefaultData</DefaultData>
<IdLocation>^UnitTest.App469.NotJSONAdaptedD</IdLocation>
<IndexLocation>^UnitTest.App469.NotJSONAdaptedI</IndexLocation>
<StreamLocation>^UnitTest.App469.NotJSONAdaptedS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

