Class UnitTest.isc.json.sample.subItemPersistent Extends (%Persistent, UnitTest.isc.json.sample.subItem)
{

Storage Default
{
<Data name="subItemPersistentDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Value</Value>
</Value>
</Data>
<DataLocation>^UnitTest.i7E30.subItemPersDA1AD</DataLocation>
<DefaultData>subItemPersistentDefaultData</DefaultData>
<IdLocation>^UnitTest.i7E30.subItemPersDA1AD</IdLocation>
<IndexLocation>^UnitTest.i7E30.subItemPersDA1AI</IndexLocation>
<StreamLocation>^UnitTest.i7E30.subItemPersDA1AS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

